#########################################################################################################
# 001-HEADER
#########################################################################################################
# menu
menu:
    home: /
    archive: /archives
    categories: /categories
    tags: /tags
    about: /about
    gallery: /gallery
    easteregg: /easteregg

# favicon & logo
favicon: /img/302.ico
logo: /img/pig.png

# background_image
# mask_alpha: 0 ~ 1
# mode: normal | random_you | random_other
# normal_url: /img/header-bg.jpg
# random_you_url: https://sariay.github.io/Random-img/
# random_other_url: https://source.unsplash.com/collection/954550/1920x1080 | https://api.berryapi.net/?service=App.Bing.Images&day=-0
mask_alpha: 0.4
background_image:
    mode: random_you
    normal_url: https://thirty-1302773433.cos.ap-nanjing.myqcloud.com/Randomimg/22.jpg
    random_you_max: 1802
    random_you_url: https://thirty-1302773433.cos.ap-nanjing.myqcloud.com/Random-img/final-version/
    random_other_url: https://thirty-1302773433.cos.ap-nanjing.myqcloud.com/Random-img/final-version/
# motto 
# source: local | hitokoto
motto:
	enable: true
	source: local
    
#########################################################################################################
# 002-PROLOADER
#########################################################################################################
# animation: spinner | transition | cyclic
preloader:
    enable: false
    animation: spinner

#########################################################################################################
# 003-INDEX
#########################################################################################################
# index-style: pure | cart
index_style: cart

# index_cart_cover
cover: /img/cart_cover.jpg
lazy_image: /img/9.gif

#########################################################################################################
# 004-POST
#########################################################################################################
# post_relate
relate:
    enable: false
    posts_limit: 1
    posts_excerpt: 50

# post_comment
comment:
    enable: true

gitalk:
    enable: false
    clientID: 12f1c02b008a8e23cbe9
    clientSecret: 0edc41dda7164d07ef197f02f581899aceb39a55
    repo: blog-of-bob
    owner: drinktoomuchsks
    admin: drinktoomuchsks
    distractionFreeMode: true
    #去除 more、index.html、?query=123等格式尾部 
    hrefTrimend: '#.*$,\\?.*$,index.html$' 
    
valine: 
    enable: false
    appid: 'DU--'
    appkey: 'DU--'
    placeholder: no any!
    
livere: 
    enable: false
    livere_uid: 'sdd'
    
# post_count
leancloud_count:
    enable: false
    appid: 'AU8...'
    appkey: '4cU...'
    serverURLs: 'http'
    like_post:
        enable: true
    visit_post:
        enable: true
    topN_post: 
        enable: false
        limit: 10

busuanzi_count:
    enable: true

baidu_analytics:
    enable: true
    id: a14d0fcf7dc3289247df7c810b29b42f

cnzz_analytics:
    enable: false
    id:

google_analytics:
    enable: false
    id:

tencent_analytics:
    enable: false
    id:

# post_toc
post_toc:
    enable: true
    katelog: true
    
# post_mathJax
mathjax:
  enable: true
  
# post_code
# highlight_theme: normal | night | night blue | night bright | night eighties
highlight_theme: night bright
code_copy:
    enable: true

# post_excerpt for index page
excerpt_cart: 50
excerpt_pure: 300   
excerpt_link: true

# post_share
share:
    enable: false
# https://www.addthis.com/
# 注意浏览器的内容拦截插件
addThis:
    enable: false
    id: ra-xxx
# http://share.baidu.com/code
baiduShare: 
    enable: false
    style: button # you can add slide style!
# https://www.sharethis.com/onboarding-cms/    
shareThis:
    enable: false
    id: 5c-xxx
# https://github.com/overtrue/share.js
socialShare:
    enable: false

#########################################################################################################
# 005-FOOTER
#########################################################################################################
# social links
# Check the icon in the page of Icomoon
social:
	github:
        url: http://github.com/
        icon: <span class="icon-github"></span>  
	qq: 
        url: https://user.qzone.qq.com/1317454943
        icon: <span class="icon-qq"></span>   

# copyright  
since: 2020
author: Bob

#########################################################################################################
# 006-GALLERY PAGE
#########################################################################################################
# gallery page
# gallery_format: natural | square
gallery_format: natural
# one time to load 4 rows or other count, 0 to load img automatically when scrolling.(0,1,2,3,4,5,6......)
gallery_limit: 0
# data url
gallery_data: plugin/gallerypage/data.json

#########################################################################################################
# 007-LOCAL SEARCH
#########################################################################################################
# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
    enable: true
    # if auto, trigger search by changing input
    # if manual, trigger search by pressing enter key or search button
    trigger: auto
    # show top n results per article, show all results by setting to -1
    top_n_per_article: 2

#########################################################################################################
# 008-OTHERS
#########################################################################################################
# when click, emerge heart
love:
    enable: false

# back to top
totop:
    enable: false
